apiVersion: v2
description: A Helm chart cert-manager ACME Webhook for INWX
name: cert-manager-webhook-inwx
version: 0.5.0
appVersion: 0.5.0
maintainers:
  - name: Vinzenz Stadtmueller
    url: https://git.cluster.tf/los/cert-manager-webhook-inwx
